"""Export the trained pipeline to JSON for browser-native inference.

Why this exists: a judge, a journalist or a Zain Cash subscriber should be able
to open one link and classify a message. "Clone the repo, pip install, run
streamlit" is not a deployment, and the competition brief asks for research
that ships.

The whole model is 14,352 dimensions -- two TF-IDF vocabularies, 28 signals and
one coefficient vector. That is under a megabyte of JSON, so the entire
classifier runs client-side with no server, no API key, and no message ever
leaving the device. For a tool that asks people to paste an SMS containing
their bank details, local-only is not a nice-to-have.

`web/verify_parity.py` checks the JavaScript port agrees with this pipeline on
every corpus row. Any divergence is a bug in the port, not a rounding artefact.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import joblib
import numpy as np

import signals
from normalize import (
    INVISIBLE, LETTER_FOLD, LONG_NUM_RE, MONEY_RE, PHONE_RE, TATWEEL, URL_RE,
    console_utf8,
)

ROOT = Path(__file__).resolve().parent.parent
MODEL_PATH = ROOT / "models" / "model.joblib"
OUT_PATH = ROOT / "web" / "model.json"


def export(model_path: Path = MODEL_PATH, out: Path = OUT_PATH) -> dict:
    bundle = joblib.load(model_path)
    pipe = bundle["pipeline"]
    fu = pipe.named_steps["features"]
    clf = pipe.named_steps["clf"]

    blocks = {}
    offset = 0
    order = []
    for name, blk in fu.transformer_list:
        if name == "signals":
            scale = blk.named_steps["scale"].scale_
            blocks["signals"] = {
                "offset": offset,
                "size": int(scale.shape[0]),
                "scale": [float(s) for s in scale],
                "names": signals.FEATURE_NAMES,
            }
            offset += int(scale.shape[0])
        else:
            vec = blk.named_steps["tfidf"]
            # vocabulary_ maps term -> column index within this block.
            vocab = sorted(vec.vocabulary_.items(), key=lambda kv: kv[1])
            terms = [t for t, _ in vocab]
            idf = vec.idf_
            blocks[name] = {
                "offset": offset,
                "size": len(terms),
                "terms": terms,
                "idf": [float(x) for x in idf],
                "ngram_range": list(vec.ngram_range),
                "sublinear_tf": bool(vec.sublinear_tf),
                "analyzer": vec.analyzer,
            }
            offset += len(terms)
        order.append(name)

    scam_idx = list(clf.classes_).index("scam")
    coef = clf.coef_[0]
    intercept = float(clf.intercept_[0])
    # LogisticRegression with binary classes scores class_[1]. Flip if 'scam'
    # is not that class, so the exported vector always scores 'scam'.
    if scam_idx == 0:
        coef, intercept = -coef, -intercept

    payload = {
        "meta": {
            "model": bundle.get("model"),
            "n_rows": bundle.get("n_rows"),
            "classes": [str(c) for c in clf.classes_],
            "dims": int(offset),
            "note": "Scores P(scam). Generated by src/export_web.py.",
        },
        "order": order,
        "blocks": blocks,
        "coef": [float(c) for c in coef],
        "intercept": intercept,
        "normalize": {
            "invisible": list(INVISIBLE),
            "tatweel": TATWEEL,
            "letter_fold": LETTER_FOLD,
            # Ported as literal source so the JS cannot silently drift.
            "diacritics_re": "[\\u064B-\\u065F\\u0670\\u06D6-\\u06ED]",
        },
        "regex": {
            "url": URL_RE.pattern,
            "phone": PHONE_RE.pattern,
            "money": MONEY_RE.pattern,
            "long_num": LONG_NUM_RE.pattern,
        },
        "signals": {
            "feature_names": signals.FEATURE_NAMES,
            "lexicons": {
                "urgency": signals.URGENCY_N,
                "prize": signals.PRIZE_N,
                "sensitive": signals.SENSITIVE_N,
                "asks_for_code": signals.ASKS_CODE_N,
                "provides_code": signals.PROVIDES_CODE_N,
                "action_link": signals.ACTION_LINK_N,
                "pay_fee": signals.PAY_FEE_N,
            },
            "brands": signals.BRANDS_N,
            "legit_domains": sorted(signals.LEGIT_DOMAINS),
            "shorteners": sorted(signals.SHORTENERS),
            "suspicious_tlds": sorted(signals.SUSPICIOUS_TLDS),
            "brand_tokens": list(signals.BRAND_TOKENS),
        },
    }

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps(payload, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )
    return payload


def main() -> None:
    console_utf8()
    ap = argparse.ArgumentParser(description="Export the model for the web demo.")
    ap.add_argument("--model", type=Path, default=MODEL_PATH)
    ap.add_argument("--out", type=Path, default=OUT_PATH)
    args = ap.parse_args()

    payload = export(args.model, args.out)
    size = args.out.stat().st_size
    print(f"dims        : {payload['meta']['dims']}")
    for name in payload["order"]:
        b = payload["blocks"][name]
        print(f"  {name:8s} offset {b['offset']:6d}  size {b['size']:6d}")
    print(f"written to  : {args.out}")
    print(f"size        : {size/1024:.0f} KB ({size/1024/1024:.2f} MB)")


if __name__ == "__main__":
    main()
